### ISSUE TITLE
can not select from subquery

### ISSUE THREAD

**Issue by knightwu** [harelba/q#102]
the query is listed below:
```
q "select * from ( select * from ./tmp.txt) a"
```
It turns out that q recognize the subquery as a file and give me the error
`File ( has not been found`

**Comment by bitti** [comment]
Just nest it like this:

    q "select * from "<(q "select * from ./tmp.txt")" a"

**Comment by harelba** [comment]
Hi,

Subqueries are supported currently only in the where clause.

@bitti 's solution (Thanks!) solves the problem using standard linux bash - The <(cmd) contruct tells bash to run this command, and replace it with a temporary filename (actually a file descriptor) which will contain the data.

If you're still having any issues, please contact me.
Harel

**Comment by harelba** [comment]
Closing this one as it's a subset of #12 

Fixes regarding it will be notified in #12.

**Comment by knightwu** [comment]
That solution can not solve the problem like this:
"select avg(a.cost) as 19_cost, avg(b.cost) as 0_cost, avg(a.qcost) as 19_qcost, avg(b.qcost) as 0_qcost from 
(select c37 as url, avg(c3) as cost, avg(c10) as qcost from 19.csv group by url) a 
join 
(select c37 as url, avg(c3) as cost, avg(c10) as qcost from 0.csv group by url) b on a.url == b.url where a.cost > b.cost"

Any Help?

**Comment by bitti** [comment]
You can use `-O` for output headers and `-H` for input header detection:

```
q -H 'select avg(a.cost) as cost_19, avg(b.cost) as cost_0, avg(a.qcost) as qcost_19, avg(b.qcost) as qcost_0 
from 
'<(q -O 'select c37 as url, avg(c3) as cost, avg(c10) as qcost from 19.csv group by url')' a 
join 
'<(q -O 'select c37 as url, avg(c3) as cost, avg(c10) as qcost from 0.csv group by url')' b on a.url == b.url where 
a.cost > b.cost'
```

Btw. `19_cost` etc are not valid qualifiers since they start with a number.

**Comment by harelba** [comment]
@knightwu - @bitti 's solution (thanks!) should be working well.

Please note that if you already have column names which start with a number, such as ````19_cost````, you can use them by wrapping the column names with backticks (Identical to sqlite's way of escaping identifiers). Be aware, though, that in order to pass backticks to q, you'd need to use single-quotes around the query itself and not double quotes, otherwise linux will interpret the backticks on its own, and this is not what you want. Example below.

If you still have a problem, I'd be glad to hear about it.

Harel

````
q -H -O 'select avg(a.cost) as `19_cost`, avg(b.cost) as 0_cost, avg(a.qcost) as 19_qcost, avg(b.qcost) as 0_qcost from ... where `19_cost` > 1000'
````
