### ISSUE TITLE
please port it to python3

### ISSUE THREAD

**Issue by zaxebo1** [harelba/q#109]
Almost all the python packages have been ported to python3 
Arch is already running fully on python3 as python default.
and Fedora 23 is having python3 as default python. 
Ubuntu 16.04 LTS also will have python3 as default python. Meaning the last bits of remaining python2 exclusive code of OS is being ported.

---

Now, If i run q on my ArchLinux, only this tool will be using python2; which seems very problematic, because then i will have to use its API using ipython2 only. I will not be able to use ipython3 for using its API. but rest of our APIs and tools are in ipython3 installation.

---

using "six" library etc , you can very easily port q to python 2.x and python 3.x from the same codebase.

**Comment by jungle-boogie** [comment]
:+1:

**Comment by harelba** [comment]
@zaxebo1 Thanks for the information. I didn't know about six - I'll take a look and try to integrate it in the next version.

**Comment by zaxebo1** [comment]
probably these will link will be also of some use use to you : 

http://python-future.org/compatible_idioms.html   (Very important)

http://python-future.org/

https://docs.python.org/2/library/2to3.html

**Comment by NDevox** [comment]
What are the main roadblocks leading to this? I'm interested in helping if possible.

**Comment by harelba** [comment]
@NDevox sorry for the late reply. 

The real block is making sure that the distribution logic remains compatible and working properly after the changes.

**Comment by NDevox** [comment]
You have tests covering that right?

**Comment by zaxebo1** [comment]
@NDevox:    +1

**Comment by leafonsword** [comment]
Hope support Python3 soon~

**Comment by jungle-boogie** [comment]
I hope we don't have to wait much longer for `q` to work with python3.

**Comment by harelba** [comment]
Hi, sorry for the large delay in providing a response.

@NDevox @zaxebo1 : You're both right, q's end-to-end testing would definitely cover that.

The main roadblock (aside from my having some free time...) is related to packaging. Ideally, I would have wanted a fully packaged single-executable for all OSs, preventing the users' need to actually care which python installation is used behind the scenes. Currently, however, this is not the case, and rpm/deb users need to be aware of it. In Windows I'm already using PyInstaller in order to provide a single-executable. Making the relevant changes so windows remains a single-executable is the main challenge, apart from the obvious changes in q's code (which I'm assuming are relatively minor).

So the shortest path to making it happen is providing a 2.7/3.x mutually compatible version of q, and then rebuilding the packages and making minimal changes to the packaging for all OSs. Hopefully, the changes for the windows version creation would be minimal as well - Replacing/Upgrading PyInstaller would be a larger effort that we would want to prevent.

If you have other suggestions for easy packaging that would provide a short path to it, I'd be glad to hear them. A PR from master with the relevant changes would go a great length towards this, as free time is scarce these days :) 

btw, note that according to q's Google Analytics 35% of users are Windows users, so we cannot neglect this OS :)

**Comment by NDevox** [comment]
@harelba It has been a while for both of us ;-).

Honestly, I ended up not using this lib although I found the idea really intriguing and can see myself possibly using it in the future (if it were python3). So I'm still interested in what is happening although I'm surprised this ticket popped back up.

Packaging in python is notoriously bad. Something like go would be a better option if you really wanted easy x-platform packaging. But we're in python and a new language port is a hell of a task. But I don't understand why packaging is the issue for porting to python3?

Pyinstaller should run fine in 3.x.

So I'd argue the main issue shouldn't be distribution but just porting the code. Once ported it should be able to be distributed as before with maybe some minimal changes.

With that said, I've not run pyinstaller before, I do not know the niches. Do you have any documentation for running it?



So now a question: The code itself. I took a quick gander. Everything is in a single file, with no extension, simply called `q`, correct? Why? Is there a specific design choice for putting everything in a single file like that? I understand the want for a single executable but having all the code in a single file during development sounds like a coding nightmare to me personally.

I may (strong emphasis on the may here) have a go at making everything compatible with 3 just as an experiment, but having a look at the codebase, and the emphasis on distribution right now is making me wonder what else needs to be taken into account first.


Finally @leafonsword and @jungle-boogie if you have time feel free to try and port it yourself.

As I said i have no current vested interest in this project, just a casual interest. the codebase isn't that big so a port should be relatively simple to do.

Sorry for the lengthy reply, this project is clearly proving popular so I think it would be a shame for it to be stuck as 2.7 only. But I want to understand as much as possible before putting time in.

**Comment by harelba** [comment]
Hi @NDevox ! Thanks for your interest. 

Regarding the packaging, I'm not an expert in deb/rpm packaging, but I believe the changes there should be minimal, if any. For PyInstaller, it's supposed to be supported, but the it's a very delicate software unfortunately. For example, in the latest q version, some people are experiencing a pyinstaller warning every time they're running q in Windows. Making it package q with python 2.7 executables (in Windows only) could probably be a minimal to reasonable effort, but making it package q for windows with python 3 might prove a larger effort. 

Regarding q being inside a single file - This is actually an artifact of python's packaging being notoriously bad, as you mentioned. The idea was to provide people with an easy capability to download a "single-file executable" in linux/mac environments without resorting to deb/rpm, if they want to. I would probably do it differently today, exposing q as python module that can be pip installed, and a frontend q binary that just uses it, but this is a larger effort, that requires more attention, and is unrelated to the python 3 porting.

Btw, the test-suite is essentially a set of system tests that actually run the q executable. It is quite comprehensive and completely external to the code - it tests the command line interface itself. These tests allowed me to do large scale cross-cutting changes with relative confidence.

I'm sorry I don't have time to invest in fully porting this myself. I'm too tied up with other projects at the moment, but I'd be glad to push this through and help as much as I can, if there's some help from the community.

**Comment by NDevox** [comment]
Tests are in a single file as well :stuck_out_tongue: 

I was under the impression that pyinstaller had the capabilities to merge everything into a single binary. Is this a specific problem for linux/mac?


I've had an initial stab at this, trying to figure out how much effort it would take. My opinion is that, despite the codebase not being that large, the way it is structured is going to make it a lot harder.

Having a lot of tests is good. But as you say most of these are run through the binary - so act as integration tests. This means that the tests, when failing, do not give much valuable feedback - I don't know what is broken if they fail, just that there was an error, somewhere, in the codebase.

I'm looking at this on my IDE and the actual obvious incompatible code is not a lot. The print statements need to be changed (realistically you should be using something better like logging in my opinion). Long no longer exists - but considering the use of SQLite you probably could just use int for everything anyway. Exceptions don't support `Exception, e` and instead need to be `Exception as e`. A couple import catches for moved modules. Dictionaries should just use `.items.` and use `range` instead of `xrange`.

Most of these are really small. The biggest issue will likely be unicoode -> str as all strings are unicode and can trip people up.

All of these are easily made cross compatible.

I don't personally think distribution would be an issue despite the worries on it. If the code can be written in a way that it supports 2.7 and 3.x at the same time the exact same distribution method can be used.

The issue I have is without being able to see where the tests break I cannot easily see the smaller hidden parts which need changing. I doubt there are many but as a non-user of this lib and not being knowledgeable of this codebase I don't necessarily think it would be worth my time when someone who knows the code could do it much faster.

Honestly I like the idea of porting this project but it's more work than anticipated due to my lack of knowledge of the codebase.

Q really needs three things in my opinion:

1. Unit tests which interact directly with the code so you can see what goes wrong where and how.
2. Refactoring to clean up the code - there are lots of unused variables. Ideally you'd split this up across multiple files (and combine them in the distribution process. It's ok to focus on the client experience but in reality the dev experience is still important. There are solutions which deal with both sides).
3. Porting as discussed above.

**Comment by erik-stephens** [comment]
Regarding the distribution problem, I find this option the most portable and less taxing on developers/maintainers: give users an "install python version >= i <= j" pre-requisite and then invoke your library with `pythonX -m q` (eg `python3 -m pip -h`) which can be aliased to something more user-friendly (eg `alias q='python3 -m q'` in bash).  This makes a lot of sense to me because it offloads the burden of you having to install python or figure out which flavor of python that the end-user already has installed.  Distributing your library can then become: put it in your preferred python's PYTHONPATH.

I don't see many pythonistas embrace this approach - maybe for good reasons :) I just wanted to share that as an option to help make life easier for q maintainers.

**Comment by harelba** [comment]
Hi,

Version `2.0.9` is out, which runs on python3 as well. The packaging has been changed so from now on q is distributed as a single-binary executable without any dependencies, including python 3 itself (e.g. it has its own python internally, it's not using any system python).

The new packaging is in a beta period, so I'd appreciate any feedback on it if any of you is planning on checking it out.

The links for the new version are in the News section of the [q web site](http://harelba.github.io/q/).

**Comment by harelba** [comment]
New release is out (version `3.1.6`), which is distributed as a standalone binary that requires no system python at all (compiled with python 3.8 behind the scenes).

Currently only deb and rpm are provided through the build, but it's now easy to add any other architecture that `fpm` supports. If there's still a need, I'd be glad to generate them as well.
