### ISSUE TITLE
Feature request: specifying a "comment" symbol (ignore lines starting with it)

### ISSUE THREAD

**Issue by jitbit** [harelba/q#112]
When analyzing/querying webserver log files it would be great if I could specify that "lines starting with an # symbol should be ignored", meaning that "#" is a "comment" symbol. Know what I mean? I hope I make myself clear... :))

**Comment by bitti** [comment]
why would you want that in `q` when you just can pipe your input through `sed '/^#/d'` therefore keeping the tools orthogonal according to UNIX philosophy?

**Comment by jitbit** [comment]
Because I'm on windows ;)

**Comment by harelba** [comment]
Hi @jitbit , sorry for the late reply.

q supports standard SQL comments (it actually supports all sqlite constructs, so you can just search the net for sqlite stuff as needed).

This means that you can embed comments inside the queries using "/*...*/" and using "-- .... \n" syntaxes. 

@bitti thanks :)

Harel

**Comment by jitbit** [comment]
I don't want comments inside queries. I want to IGNORE SOME LINES IN THE FILE.

**Comment by harelba** [comment]
ah... I see :)

Need to think about it. Adding special semantics above the layer of the SQL itself can be a rabbit hole, but I won't say that there can't be any exceptions.

The standard way to achieve something like that without resorting to preprocessing such as sed, would be to add another condition to the WHERE part of the sql (something like "WHERE c1 not like '#%'"). That would do the trick.

I'll give it some thought.
Harel

**Comment by jitbit** [comment]
Oh, yeah, right, probably you are right, "WHERE" will work, but usually the "column" structure inside a commented line is badly formatted...

PS. One of the reasons its a great idea is that typically log files (which I'm sure is 70% use case with your app) have some sort of commenting. Anyways, thanks for an awesome product.

**Comment by bitti** [comment]
I don't know how windows is bearable without cygwin, but even stock-windows can do something trivial like filtering a text file by a pattern: https://technet.microsoft.com/en-us/library/bb490907.aspx.

**Comment by harelba** [comment]
@jitbit Thanks for the kind words. You're right about the issue with the comment's formatting. I actually don't usually see logs with comments in them, but perhaps it's just bias from my regular day job stuff.

In terms of parsing wrongly-formatted rows such as comments, q does provide "relaxed" mode (which is actually the default in order to be able to easily handle output from many linux commands which don't provide strict tabular output), but commented lines can cause issues in column-inference in that regard (e.g. thinking that a column is a string instead of being numeric, since the comment text will be considered as data), so it won't be fully helpful.

I am aware that in the context of Windows, many users are using q as kind of a command line replacement for many of the standard linux tools, but I do agree with @bitti that in that regard q cannot be a full replacement for all the needs. Again, need to think about it - I got a request for removing comment rows from two more users, so perhaps it might be something that needs to be considered as an exception.
