### ISSUE TITLE
SUGGEST FUNCTIONS TO ADD TO Q (was - Support for computation like roots powers, etc.)

### ISSUE THREAD

**Issue by szaydel** [harelba/q#150]
I was wondering if consideration has been given to supporting functions like SQRT, POW, and perhaps STDDEV, which admittedly not standard for SQL. I think it would be great to be able to easily apply transformations like this to data.

**Comment by vi** [comment]
Bump.

["How to calculate square root in sqlite"][1] talks about some ["extension functions"][2]. Are them applicable to Q?

[1]:https://stackoverflow.com/questions/12731941/how-to-calculate-square-root-in-sqlite
[2]:http://sqlite.org/contrib/download/extension-functions.c?get=25

**Comment by harelba** [comment]
I'm already adding several extension functions: regexp(), sha1(), and percentile().

I don't mind adding several others, but i'd be glad to do it in one go, since i'm currently involved in other projects, and the overhead of issuing a version is not trivial (mainly because of the windows version actually...).

Let's make this issue a placeholder for all the functions that people require, and then i'll add them.

Just add a comment with your request.

**Comment by bitti** [comment]
Does every release has to include a Windows build? And how many people are actually waiting for a Windows release compared to a Linux/Unix release? Why not make more frequent releases for Unix and some infrequent releases with a Windows build?

**Comment by harelba** [comment]
@bitti About your suggestion to split the windows and linux version releases - The q site google analytics shows that 30% of the people that arrive to the site run on windows machines. While this doesn't necessarily indicates that this is the percentage of users, it does lead me to think that there is a relatively large base of users which are windows-based. This is why i would prefer the versions not to diverge.

**Comment by harelba** [comment]
Added `sqrt()`, `power()`, `stddev_pop`, `sha` (allows choosing the sha algorithm), `md5` functions.

Also added `-L` flag to list all user functions

**Comment by harelba** [comment]
Added functionality just released as part of 2.0.19
