### ISSUE TITLE
header not on the first line?

### ISSUE THREAD

**Issue by ryenus** [harelba/q#166]
Is it possible for the `-H` option to take an optional argument to specify where does the header line is? Some programs, like `w`, has its header on line 2. 

And certain files. such as `/etc/passwd` has some leading comments that can be skipped. What about having something like in sed to use a regular expression to specify the header line?

Thanks

**Comment by harelba** [comment]
Hi,

Part of q's concept is to integrate well with the linux command-line ecosystem, so using the relevant tools for filtering unneeded lines is preferred in my view. Here's an example with w's output:

`w | sed '1d' | q -H "select TTY from -"`

`sed` is used in this case in order to delete row number 1. If you need to delete several rows, you can pass a range to sed using '1,10d' for example. For osx users, download gsed (the gnu-sed) and use it instead. If you're a window user, then i fully understand that there is no good-enough solution for this, but i do not believe that going towards adding those capabilities into q itself would be the best approach.
