### ISSUE TITLE
Cannot encode data.

### ISSUE THREAD

**Issue by rseemann** [harelba/q#191]
I'm trying to run a query on a csv that contains accented characters, but I'm getting this error: 
`Cannot encode data. Error:'ascii' codec can't encode characters in position 3: ordinal not in range(128)`

If I remove the problematic characters it runs nicely, or if I limit the query to return rows that do not contain the problematic characters it also works. I tried reencoding the file to UTF-8, but it seems this does not fix the problem.

```
id,text
1,normal
2,não
```

works - `q -H  -d , "select * from ut.csv where id = 1"`
doesn't work - `q -H  -d , "select * from ut.csv where id = 2"`

using `-e utf-8-sig` also doesn't seem to have any effect.

Could you please lend a hand? :)

Cheers

**Comment by harelba** [comment]
Hi, sorry for the late reply.

I think it depends on your "native" encoding. In my terminal both work well, but i believe that this is because my native encoding it utf-8, so the copy-paste i did from your message above was utf-8 as well. 

I would need two things in order to try to help:
1. Upload of the actual file that causes you issues (send it as a zip file, so there won't be any incidental encoding/re-encoding)
2. Information about your computer - OS, native encoding, etc.
3. the output of `file X` on this file on your terminal (assuming you're on osx/linux...)

Harel

**Comment by harelba** [comment]
@rseemann kind reminder to this issue. I'd be glad to help if needed.

**Comment by rseemann** [comment]
Hi @harelba, thanks for the reply!

I had a similar problem in another project, and I fixed it with utf-8. I'll close this thread since I believe it might be the same problem and reopen if I can't solve it then, does that make sense?

**Comment by rseemann** [comment]
Curiously enough I was trying to run the command from within a Python script and it works

`output = subprocess.check_output(['bash','-c', bashCommand])`

but if I try to run the exact same command from the command-line it gives me the ascii error. I no expert in bash, so it might be something obvious here that I might be missing.
