### ISSUE TITLE
x32 executables for q 2.x.x

### ISSUE THREAD

**Issue by Shtirla** [harelba/q#221]
Its posible to make installer or executable
for x32 windows systems? plz

**Comment by harelba** [comment]
Hi, @Shtirla,

I'm sorry, but currently there's no plan to support 32bit systems. The reason is that there seems to be very little need for that from users.

I'm making this ticket more generic, supporting 32bit systems in general. 

If there are enough comments and upvotes, I'd be glad to make the effort.

Harel

**Comment by harelba** [comment]
Closing the ticket, as no other requests have been added.
