### ISSUE TITLE
Space in column name on TAB separated values break q

### ISSUE THREAD

**Issue by thomas-riccardi** [harelba/q#44]
```
$ echo -e "a\tb c\n1\t2" > test.tsv
$ q -H -t 'select a from -' < test.tsv
query error: near "c": syntax error
```

Spaces in non space separators should be accepted.

**Comment by dclong** [comment]
I'm still experience an issue using q of version 1.7.1. 
```
$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
dclong/jupyter-beakerx     latest              f56abf68f4a3        10 hours ago        1.55 GB
dclong/jupyter             latest              80e8b5d0beba        24 hours ago        786 MB
<none>                     <none>              d0ca316710aa        24 hours ago        963 MB
dclong/jupyter             <none>              20f490cf873c        33 hours ago        963 MB
dclong/jupyter-beakerx     <none>              8b7cbf8cd567        33 hours ago        1.73 GB
dclong/jupyterhub-ds       latest              c3366002a3d8        47 hours ago        4.67 GB
dclong/jupyterhub-tdodbc   latest              bfb4b244a144        2 days ago          1.87 GB
dclong/jupyter             <none>              cdc06da454d2        10 days ago         1.18 GB
dclong/python              latest              6f52f723366e        10 days ago         694 MB
ubuntu                     18.04               02f9d6707661        5 weeks ago         88.3 MB
```
```
$ docker images | q -T -H 'select `IMAGE ID` from -'
query error: no such column: IMAGE ID
Warning - There seems to be a "no such column" error, and -H (header line) exists. Please make sure that you are using the column names from the header line and not the default (cXX) column names

```

**Comment by bitti** [comment]
Option `-T` is for specifying TAB as an output separator. To specify it as an input separator you have to use `-t`. But is `docker images` really using TAB delimiters? Your quoted output only contains spaces. If not I would suggest replacing two or more spaces with a TAB before parsing with `q`. E.g.

    sed 's/  \+/\t/g' images|q -t -H 'select `IMAGE ID` from -'

**Comment by bitti** [comment]
@dclong I don't know what you mean by "bracket". And double quote strings works perfectly fine in sqlite (for which `q` is basically a wrapper for). But even if you want to use single quotes you can just escape them.

Of course if you use double quotes for the `q` query parameter you have to be aware that backticks will trigger shell evaluations in bash (and probably some other shells). That's why I suggested to @harelba a while ago to use single quotes in the examples to avoid confusions which he did: https://github.com/harelba/q/issues/94#issuecomment-276610049.

**Comment by contentfree** [comment]
Just wanted to drop this here that I'm witnessing the same behavior with 1.7.1 (using both `-t` and `-d$'\t'` and trying both backticks and brackets in the query). Using `--analyze` shows all the expected columns (with backticks). I copy and paste the name from the `--analyze` output; doesn't work.

Is it possible that a Unicode BOM causes the issue?

**Comment by contentfree** [comment]
Yep. Confirming: A UTF-8 with BOM breaks `q`. New issue?

**Comment by harelba** [comment]
Just for completeness, I'll summarize the `docker images` issue - This command unfortunately does not provide a real table-like structure, since both the delimiters between fields and the character between `IMAGE` and `ID` are both spaces. One option is to pipe the command through `sed '1s/IMAGE ID/IMAGE_ID/'` in order to make it table-like again. However, in either case, the `-t` parameter is not the proper delimiter for processing the output of this command. 

For historical reasons, q's default delimiter is space and not a tab/comma, so apart from adding the `sed` command above, no delimiter parameter is needed. Btw, `-T` indeed decides the *output* delimiter to be a tab, which is not related to the issue at hand.

@contentfree  Regarding UTF-8 with BOM, i have hacked support for this a long time ago, working around a bug in the csv module regarding handling it. It should be working but you need to provide the encoding as a parameter. Add `-e utf-8-sig` to the command line. I would appreciate opening a new ticket for this with an example if it doesn't solve the problem.

**Comment by bitti** [comment]
I finally understand what @dclong meant. sqlite also supports `[...]` to escape columns for "compatibility" with MS based DBs. Similarly backticks are just supported for mysql compatibility. According to the [official documentation](https://www.sqlite.org/lang_keywords.html) double quotes should be used though. So maybe that's also what should be used in the examples of the `q` documentation?
