### ISSUE TITLE
Feature Request: Enable writing out cached data for performance increase

### ISSUE THREAD

**Issue by dalemyers** [harelba/q#96]
When dealing with large files, the queries can take a very long time. Being able to keep the created sqlite db on disk and then query it again would make this much faster for successive runs.

**Comment by harelba** [comment]
Hi @Vel0x , sorry fro the late reply.

You're right, and I have plans to do this. I've made some preparations for this in the latest 1.5.0 version, and hopefully it will be part of the next version. 

In the mean time, there is partial support for something which might help you - You can run multiple queries on the same command line and the data will be loaded only once:

`q "select .... from A" "select .... from B" "select ... from A" `

In this example, A and will will be loaded only once - The third query will run almost instantly since A is already loaded.

By the way, I'm also planning on an interactive mode for the next version, which will make use of this capability and will allow to run multiple queries on the same data without reloading.

Harel

**Comment by Vel0x** [comment]
That sounds pretty awesome. I was planning on having a look into doing it my self this weekend, but it seems like you are already way ahead of me!

Thanks

**Comment by ajmazurie** [comment]
I am revisiting this issue. I have GB to TB-sized CSV files I'd like to slice and dice using **q**, and would like to save the intermediate `sqlite` data object as a file for further processing. Best, Aurélien

**Comment by dalemyers** [comment]
Just going through my old issues and this is still open. I don't need this functionality any more, but I'm curious if it was ever added?

**Comment by bitti** [comment]
A few GB might be still feasible, but if you get into the TB range I doubt that q is the right tool for that. I always found q a nice postprocessing tool, e.g. when querying the results of some mapreduce jobs. It certainly is not suited to do the processing of large files itself.

**Comment by dalemyers** [comment]
At the time, I was working with files a few hundred MB. It's enough that caching is nice if you are going back and forth multiple times in a script.

**Comment by harelba** [comment]
sorry for the late reply,

q has a variation on this - You can ask it to save the data to an sqlite database file, and then analyze it with sqlite command line.

````
  -S SAVE_DB_TO_DISK_FILENAME, --save-db-to-disk=SAVE_DB_TO_DISK_FILENAME
                        Save database to an sqlite database file
````

Regardless, if you're dealing with huge files, then you'd probably need to use some distributed solution and not q. I once had done some steps of making q's engine work with apache spark behind the scenes, and a POC was indeed working, but I eventually didn't pursue this to become full fledged production grade.

**Comment by dalemyers** [comment]
That sounds good enough for what I need(ed)!
